<?php

namespace Proxies\__CG__\AccueilBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reservation extends \AccueilBundle\Entity\Reservation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'billets', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'id', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'email', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'dateJour', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'demiJournee', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'dateResa', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'prixTotal', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'stripeToken');
        }

        return array('__isInitialized__', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'billets', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'id', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'email', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'dateJour', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'demiJournee', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'dateResa', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'prixTotal', '' . "\0" . 'AccueilBundle\\Entity\\Reservation' . "\0" . 'stripeToken');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Reservation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateJour($dateJour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateJour', array($dateJour));

        return parent::setDateJour($dateJour);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateJour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateJour', array());

        return parent::getDateJour();
    }

    /**
     * {@inheritDoc}
     */
    public function getBillet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillet', array());

        return parent::getBillet();
    }

    /**
     * {@inheritDoc}
     */
    public function setDemiJournee($demiJournee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDemiJournee', array($demiJournee));

        return parent::setDemiJournee($demiJournee);
    }

    /**
     * {@inheritDoc}
     */
    public function getDemiJournee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDemiJournee', array());

        return parent::getDemiJournee();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateResa($dateResa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateResa', array($dateResa));

        return parent::setDateResa($dateResa);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateResa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateResa', array());

        return parent::getDateResa();
    }

    /**
     * {@inheritDoc}
     */
    public function addBillet(\AccueilBundle\Entity\Billet $billets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBillet', array($billets));

        return parent::addBillet($billets);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBillet(\AccueilBundle\Entity\Billet $billets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBillet', array($billets));

        return parent::removeBillet($billets);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillets', array());

        return parent::getBillets();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixTotal($prixTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixTotal', array($prixTotal));

        return parent::setPrixTotal($prixTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixTotal', array());

        return parent::getPrixTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setStripeToken($stripeToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStripeToken', array($stripeToken));

        return parent::setStripeToken($stripeToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getStripeToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStripeToken', array());

        return parent::getStripeToken();
    }

}
